version: '3'
services:
  react-app:
    #there's only a Dockerfile.dev file, no default Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      #do not attempt to map a folder against node_modules inside the container
      - /home/node/app/node_modules
      #map the project folder outside the container into the /app folder inside the container 
      - .:/home/node/app
